### PR TITLE
Refactor case api

### PR DESCRIPTION
**Pull request by endamccormack**

### CODE REVIEW

**Comment by endamccormack** [comment]
Few extra changes including a bug found and extra feature that need adding

**Comment by endamccormack** [comment]
Refactor is done, fixed 2 bugs the major one being the /case rendering wrong, good catch @michaeldfallen 

The api map is not ideal and any comments welcome
screen shot 2015-09-10 at 19 03 23

**Comment by dawidskainos** [comment]
:+1:

**Comment by tsangsimon** [comment]
Enda, Regarding the API Map, could you add what parameters are expected for the POST routes.

**Pull request merged**
